FROM ubuntu:focal

RUN apt update && apt install -y --no-install-recommends \
    iputils-ping \
    python3 \
    ffmpeg \
    wget \
    ca-certificates \
    && rm -rf /var/lib/apt/lists/*

# To make this device vulnerable to Mirai, we need a telnet server and the busybox shell.
# busybox from Debian repos does not include 'telnetd'.
# By default, this does not make it vulnerable because telnetd is not running automatically.
RUN wget https://busybox.net/downloads/binaries/1.35.0-x86_64-linux-musl/busybox &&\
    chmod +x busybox &&\
    mv busybox /bin &&\
    printf '#!/bin/sh\n/bin/busybox sh\n' > /bin/busyboxsh &&\
    chmod +x /bin/busyboxsh

COPY museum_lebanon.mp4 /original.mp4
COPY ip_camera.py /ip_camera.py
RUN chmod +x /ip_camera.py

# ffmpeg
# -an      : remove audio
# -r       : set frame rate in fps
# -s:v     : set video frame size wxh
# -filter:v "hue=s=0" : grayscale
# -codec:v : video format
RUN ffmpeg -i /original.mp4 -an -r 25 -s:v 1280x720 -filter:v "hue=s=0" -codec:v libx264 /video.mp4 &&\
    rm -f /original.mp4 &&\
    ffprobe /video.mp4 &&\
    ls -lh /video.mp4

ENTRYPOINT [ "/ip_camera.py" ]
